#!/bin/bash
man="trackr - track the time

DESCRIPTION
        Track how much time was spent on a task.

USAGE
        trackr \"[TASK]\""

if [[ -z $1 ]] || [[ $1 == -h ]]; then echo "$man"; exit; fi

task=$1
date_started=$(date)

trap save_stats SIGINT
save_stats() {
  printf "\"$date_started\",\"$(date)\",\"$task\",\"$time_elapsed\"\n" \
    >> ../out/trackr.txt
  printf "\rYou focused on \"$task\" for: $time_elapsed"
  echo ""
  exit
}

while true; do
  ((second++))

  if [[ $second == 60 ]]; then second=0; ((minute++)); fi
  if [[ $minute == 60 ]]; then minute=0; ((hour++)); fi
  if [[ $hour == 24 ]]; then hour=0; ((day++)); fi

  time_elapsed="$second'\bs"
  [[ "$minute" -gt "0" ]] && time_elapsed="$minute'\bm $time_elapsed"
  [[ "$hour" -gt "0" ]] && time_elapsed="$hour'\bh $time_elapsed"
  [[ "$day" -gt "0" ]] && time_elapsed="$day'\bd $time_elapsed"

  printf "\r$task  ====  $time_elapsed"
  sleep 1
done
