#!/bin/bash
man="xscripts - scripts for X

DESCRIPTION
        A set of functions to automate the X environment

ARGUMENTS
        -v, --visual
            set X resources, open a terminal and kill it after 5 seconds

        -k, --keyboard
            set Xorg keyboard layout

        -r [y] [x], --resize [y] [x]
            integers that corresponds to xterm lines and rows, respectively"

set_and_view_x_resources () {
  xrdb ~/.Xresources
  $TERM &>/dev/null &
  sleep 5s
  kill -9 $! &>/dev/null
  exit
}

set_keyboard_layout () {
  setxkbmap $1
  exit
}

resize_terminal () {
  re='^[0-9]+$'
  if [[ -z $1 ]] || [[ -z $2 ]] || ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]]; 
  then 
    echo "$man"
    exit
  fi
  
  printf "\033[8;$1;$2t"
  exit
}


[[ "$1" == "-v" || "$1" == "--visual" ]] && set_and_view_x_resources
[[ "$1" == "-k" || "$1" == "--keyboard" ]] && set_keyboard_layout $2
[[ "$1" == "-r" || "$1" == "--resize" ]] && resize_terminal $2 $3

echo "$man"
