#!/bin/bash
man="xscipts - scripts for X

DESCRIPTION
        A set of functions to automate the X environment

USAGE
        xscripts \"[-r]\"

ARGUMENTS
        -r, --resize
          reload X resources, open a terminal and kill it after 5 seconds"

reload_and_preview_x_resources () {
  xrdb ~/.Xresources
  $TERM &>/dev/null &
  sleep 5s
  kill -9 $! &>/dev/null
}

[[ "$1" == "-r" || "$1" == "--reload" ]] && reload_and_preview_x_resources
